-- MySQL Script generated by MySQL Workbench
-- Mon Oct  2 10:11:09 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `denomination` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idtype_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`etablisement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`etablisement` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL DEFAULT 'Mami Clafoutis',
  `adresse` VARCHAR(255) NOT NULL,
  `tel` VARCHAR(12) NOT NULL,
  `type_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idetablisement_UNIQUE` (`id` ASC),
  UNIQUE INDEX `adresse_UNIQUE` (`adresse` ASC),
  UNIQUE INDEX `tel_UNIQUE` (`tel` ASC),
  INDEX `fk_etablisement_type_idx` (`type_id` ASC),
  CONSTRAINT `fk_etablisement_type`
    FOREIGN KEY (`type_id`)
    REFERENCES `mydb`.`type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`role` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `denomination` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`utilisateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`utilisateur` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(50) NOT NULL,
  `prenom` VARCHAR(50) NOT NULL,
  `etablisement_id` INT NOT NULL,
  `role_id` INT NOT NULL,
  `userName` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idUser_UNIQUE` (`id` ASC),
  INDEX `fk_User_etablisement1_idx` (`etablisement_id` ASC),
  INDEX `fk_utilisateur_role1_idx` (`role_id` ASC),
  UNIQUE INDEX `userName_UNIQUE` (`userName` ASC),
  CONSTRAINT `fk_User_etablisement1`
    FOREIGN KEY (`etablisement_id`)
    REFERENCES `mydb`.`etablisement` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_utilisateur_role1`
    FOREIGN KEY (`role_id`)
    REFERENCES `mydb`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`commande`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`commande` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `utilisateur_id` INT NOT NULL,
  `date` VARCHAR(45) NOT NULL,
  `valide` TINYINT(1) NOT NULL DEFAULT 0,
  `ref` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_commande_utilisateur1_idx` (`utilisateur_id` ASC),
  CONSTRAINT `fk_commande_utilisateur1`
    FOREIGN KEY (`utilisateur_id`)
    REFERENCES `mydb`.`utilisateur` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`categorie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`categorie` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `denomination` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`produit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`produit` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(255) NOT NULL,
  `categorie_id` INT NOT NULL,
  `ref` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idproduit_UNIQUE` (`id` ASC),
  INDEX `fk_produit_categorie1_idx` (`categorie_id` ASC),
  UNIQUE INDEX `ref_UNIQUE` (`ref` ASC),
  CONSTRAINT `fk_produit_categorie1`
    FOREIGN KEY (`categorie_id`)
    REFERENCES `mydb`.`categorie` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ligne de commande`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ligne de commande` (
  `commande_id` INT NOT NULL,
  `produit_idproduit` INT NOT NULL,
  `quantite` INT NOT NULL,
  PRIMARY KEY (`commande_id`, `produit_idproduit`),
  INDEX `fk_ligne de commande_produit1_idx` (`produit_idproduit` ASC),
  CONSTRAINT `fk_ligne de commande_commande1`
    FOREIGN KEY (`commande_id`)
    REFERENCES `mydb`.`commande` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ligne de commande_produit1`
    FOREIGN KEY (`produit_idproduit`)
    REFERENCES `mydb`.`produit` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ingredient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ingredient` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `denomination` VARCHAR(255) NOT NULL,
  `quantite` INT NOT NULL,
  `unite_ingredient` VARCHAR(255) NOT NULL,
  `ref` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `denomination_UNIQUE` (`denomination` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `ref_UNIQUE` (`ref` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ligne ingredient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ligne ingredient` (
  `ingredient_id` INT NOT NULL,
  `produit_id` INT NOT NULL,
  `quantite` FLOAT NOT NULL,
  `unite` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ingredient_id`, `produit_id`),
  INDEX `fk_ligne ingredient_produit1_idx` (`produit_id` ASC),
  CONSTRAINT `fk_ligne ingredient_ingredient1`
    FOREIGN KEY (`ingredient_id`)
    REFERENCES `mydb`.`ingredient` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ligne ingredient_produit1`
    FOREIGN KEY (`produit_id`)
    REFERENCES `mydb`.`produit` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`recette`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`recette` (
  `produit_id` INT NOT NULL,
  `url recette` VARCHAR(255) NOT NULL,
  `denomination` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`produit_id`),
  CONSTRAINT `fk_recette_produit1`
    FOREIGN KEY (`produit_id`)
    REFERENCES `mydb`.`produit` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ventes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ventes` (
  `date_horaire` VARCHAR(45) NOT NULL,
  `utilisateur_id` INT NOT NULL,
  `quantite` VARCHAR(45) NOT NULL,
  `produit_id` INT NOT NULL,
  PRIMARY KEY (`produit_id`, `utilisateur_id`, `date_horaire`),
  INDEX `fk_ventes_utilisateur1_idx` (`utilisateur_id` ASC),
  INDEX `fk_ventes_produit1_idx` (`produit_id` ASC),
  CONSTRAINT `fk_ventes_utilisateur1`
    FOREIGN KEY (`utilisateur_id`)
    REFERENCES `mydb`.`utilisateur` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ventes_produit1`
    FOREIGN KEY (`produit_id`)
    REFERENCES `mydb`.`produit` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`production`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`production` (
  `utilisateur_id` INT NOT NULL,
  `produit_id` INT NOT NULL,
  `quantite` INT NOT NULL,
  `date` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`utilisateur_id`, `produit_id`, `date`),
  INDEX `fk_production_produit1_idx` (`produit_id` ASC),
  CONSTRAINT `fk_production_utilisateur1`
    FOREIGN KEY (`utilisateur_id`)
    REFERENCES `mydb`.`utilisateur` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_production_produit1`
    FOREIGN KEY (`produit_id`)
    REFERENCES `mydb`.`produit` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
